import { Product } from '../types';
import mariagePrestige from '../assets/images/mariage_prestige_1780566116217.png';
import bouteillesJus from '../assets/images/bouteilles_jus_1780566133711.png';
import packCosmetique from '../assets/images/pack_cosmetique_1780566149588.png';
import objetsPublicitaires from '../assets/images/objets_publicitaires_1780566164378.png';
import accessoiresPack from '../assets/images/accessoires_pack_1780566177329.png';

const now = new Date().toISOString();

export const productsData: Product[] = [

  // SACS & EMBALLAGES BOUTIQUE
  { id: 'sac-kraft', name: 'Sacs Kraft', price: 180, category: 'sacs-emballages-boutique', subcategory: 'Sacs papier', images: [accessoiresPack], description: 'Sacs en papier Kraft résistants et biodégradables, personnalisables avec votre logo.', minQty: 500, productionDelay: '5-7 jours', isCustomizable: true, stock: 25000, rating: 4.8, reviewsCount: 32, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
  { id: 'sac-papier-blanc', name: 'Sacs Papier Blanc', price: 200, category: 'sacs-emballages-boutique', subcategory: 'Sacs papier', images: [accessoiresPack], description: 'Sacs papier blanc de qualité supérieure pour boutiques et commerces.', minQty: 300, productionDelay: '5-7 jours', isCustomizable: true, stock: 20000, rating: 4.7, reviewsCount: 18, disponibilite: 'en_stock', produit_mis_en_avant: false, date_creation: now, date_modification: now },
  { id: 'sac-papier-luxe', name: 'Sacs Papier Luxe', price: 650, category: 'sacs-emballages-boutique', subcategory: 'Sacs papier', images: [mariagePrestige], description: 'Sacs luxe avec poignées ruban satin, finition mate veloutée.', minQty: 100, productionDelay: '7-10 jours', isCustomizable: true, stock: 5000, rating: 5.0, reviewsCount: 18, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
  { id: 'tote-bag', name: 'Tote Bags Personnalisés', price: 450, category: 'sacs-emballages-boutique', subcategory: 'Sacs personnalisés', images: [accessoiresPack], description: 'Tote bags en coton personnalisés avec votre logo ou design.', minQty: 100, productionDelay: '7-10 jours', isCustomizable: true, stock: 10000, rating: 4.9, reviewsCount: 25, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
  { id: 'sac-cadeau', name: 'Sacs Cadeaux', price: 350, category: 'sacs-emballages-boutique', subcategory: 'Sacs cadeaux', images: [mariagePrestige], description: 'Sacs cadeaux élégants pour toutes occasions.', minQty: 200, productionDelay: '5-7 jours', isCustomizable: true, stock: 8000, rating: 4.8, reviewsCount: 22, disponibilite: 'en_stock', produit_mis_en_avant: false, date_creation: now, date_modification: now },

  // EMBALLAGES ALIMENTAIRES
  { id: 'barquette-kraft', name: 'Barquettes Kraft', price: 85, category: 'emballages-alimentaires', subcategory: 'Barquettes', images: [accessoiresPack], description: 'Barquettes Kraft avec couvercle, idéales pour plats chauds et froids.', minQty: 1000, productionDelay: '3-5 jours', isCustomizable: false, stock: 50000, rating: 4.8, reviewsCount: 45, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
  { id: 'boite-repas', name: 'Boîtes Repas', price: 120, category: 'emballages-alimentaires', subcategory: 'Boîtes alimentaires', images: [accessoiresPack], description: 'Boîtes repas hermétiques pour la restauration et la livraison.', minQty: 500, productionDelay: '3-5 jours', isCustomizable: true, stock: 30000, rating: 4.7, reviewsCount: 38, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
  { id: 'papier-kraft-alimentaire', name: 'Papier Kraft Alimentaire', price: 45, category: 'emballages-alimentaires', subcategory: 'Consommables alimentaires', images: [accessoiresPack], description: 'Papier Kraft alimentaire pour emballage sandwich et burger.', minQty: 2000, productionDelay: '2-3 jours', isCustomizable: false, stock: 100000, rating: 4.6, reviewsCount: 29, disponibilite: 'en_stock', produit_mis_en_avant: false, date_creation: now, date_modification: now },
  { id: 'serviettes', name: 'Serviettes Personnalisées', price: 35, category: 'emballages-alimentaires', subcategory: 'Accessoires', images: [accessoiresPack], description: 'Serviettes en papier personnalisées avec votre logo.', minQty: 2000, productionDelay: '5-7 jours', isCustomizable: true, stock: 80000, rating: 4.5, reviewsCount: 20, disponibilite: 'en_stock', produit_mis_en_avant: false, date_creation: now, date_modification: now },

  // GOBELETS & BOISSONS
  { id: 'gobelet-250ml', name: 'Gobelets 250ml', price: 65, category: 'gobelets-boissons', subcategory: 'Gobelets', images: [bouteillesJus], description: 'Gobelets carton 250ml personnalisables pour café, jus et boissons chaudes.', minQty: 1000, productionDelay: '5-7 jours', isCustomizable: true, stock: 40000, rating: 4.8, reviewsCount: 52, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
  { id: 'gobelet-kraft', name: 'Gobelets Kraft', price: 75, category: 'gobelets-boissons', subcategory: 'Gobelets', images: [bouteillesJus], description: 'Gobelets en carton Kraft naturel, aspect eco-friendly.', minQty: 500, productionDelay: '5-7 jours', isCustomizable: true, stock: 20000, rating: 4.7, reviewsCount: 31, disponibilite: 'en_stock', produit_mis_en_avant: false, date_creation: now, date_modification: now },
  { id: 'bouteille-jus', name: 'Bouteilles de Jus', price: 250, category: 'gobelets-boissons', subcategory: 'Bouteilles', images: [bouteillesJus], description: 'Bouteilles pour jus locaux, formats standards et sur mesure.', minQty: 200, productionDelay: '7-10 jours', isCustomizable: true, stock: 15000, rating: 4.9, reviewsCount: 41, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },

  // FAST-FOOD & RESTAURATION
  { id: 'boite-burger', name: 'Boîtes à Burger', price: 95, category: 'fast-food-restauration', subcategory: 'Fast-food', images: [accessoiresPack], description: 'Boîtes burger personnalisables, résistantes à la chaleur et aux graisses.', minQty: 500, productionDelay: '5-7 jours', isCustomizable: true, stock: 25000, rating: 4.8, reviewsCount: 44, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
  { id: 'boite-pizza', name: 'Boîtes à Pizza', price: 150, category: 'fast-food-restauration', subcategory: 'Fast-food', images: [accessoiresPack], description: 'Boîtes pizza en carton kraft, formats 25cm à 45cm.', minQty: 300, productionDelay: '5-7 jours', isCustomizable: true, stock: 15000, rating: 4.7, reviewsCount: 28, disponibilite: 'en_stock', produit_mis_en_avant: false, date_creation: now, date_modification: now },
  { id: 'boite-tacos', name: 'Boîtes à Tacos', price: 110, category: 'fast-food-restauration', subcategory: 'Fast-food', images: [accessoiresPack], description: 'Boîtes tacos pratiques et personnalisables.', minQty: 500, productionDelay: '5-7 jours', isCustomizable: true, stock: 20000, rating: 4.6, reviewsCount: 19, disponibilite: 'en_stock', produit_mis_en_avant: false, date_creation: now, date_modification: now },

  // PATISSERIE & BOULANGERIE
  { id: 'boite-gateau', name: 'Boîtes à Gâteaux', price: 200, category: 'patisserie-boulangerie', subcategory: 'Pâtisserie', images: [mariagePrestige], description: 'Boîtes à gâteaux élégantes, personnalisables avec fenêtre transparente.', minQty: 200, productionDelay: '5-7 jours', isCustomizable: true, stock: 10000, rating: 4.9, reviewsCount: 36, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
  { id: 'boite-cupcakes', name: 'Boîtes à Cupcakes', price: 180, category: 'patisserie-boulangerie', subcategory: 'Pâtisserie', images: [mariagePrestige], description: 'Boîtes cupcakes avec insert, disponibles en 4, 6 et 12 cases.', minQty: 200, productionDelay: '5-7 jours', isCustomizable: true, stock: 8000, rating: 4.8, reviewsCount: 27, disponibilite: 'en_stock', produit_mis_en_avant: false, date_creation: now, date_modification: now },

  // BOUTEILLES PERSONNALISEES
  { id: 'bouteille-mariage', name: 'Bouteilles Mariage', price: 850, category: 'bouteilles-personnalisees', subcategory: 'Eau personnalisée', images: [bouteillesJus], description: 'Bouteilles d\'eau personnalisées pour mariages avec étiquette sur mesure.', minQty: 100, productionDelay: '7-10 jours', isCustomizable: true, stock: 5000, rating: 5.0, reviewsCount: 48, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
  { id: 'bouteille-entreprise', name: 'Bouteilles Entreprise', price: 750, category: 'bouteilles-personnalisees', subcategory: 'Eau personnalisée', images: [bouteillesJus], description: 'Bouteilles d\'eau à votre marque pour événements et cadeaux d\'entreprise.', minQty: 200, productionDelay: '7-10 jours', isCustomizable: true, stock: 8000, rating: 4.9, reviewsCount: 33, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
  { id: 'etiquette-bouteille', name: 'Étiquettes Bouteilles', price: 150, category: 'bouteilles-personnalisees', subcategory: 'Étiquettes', images: [bouteillesJus], description: 'Étiquettes autocollantes personnalisées pour bouteilles de toutes tailles.', minQty: 500, productionDelay: '3-5 jours', isCustomizable: true, stock: 30000, rating: 4.7, reviewsCount: 22, disponibilite: 'en_stock', produit_mis_en_avant: false, date_creation: now, date_modification: now },

  // PARFUMERIE & COSMETIQUE
  { id: 'flacon-50ml', name: 'Flacons 50ml', price: 450, category: 'parfumerie-cosmetique', subcategory: 'Flacons', images: [packCosmetique], description: 'Flacons verre 50ml pour parfums et cosmétiques, disponibles en spray et pompe.', minQty: 100, productionDelay: '7-10 jours', isCustomizable: true, stock: 5000, rating: 4.8, reviewsCount: 29, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
  { id: 'pot-creme', name: 'Pots de Crème', price: 350, category: 'parfumerie-cosmetique', subcategory: 'Pots cosmétiques', images: [packCosmetique], description: 'Pots cosmétiques pour crèmes, baumes et beurres corporels.', minQty: 100, productionDelay: '7-10 jours', isCustomizable: true, stock: 4000, rating: 4.7, reviewsCount: 18, disponibilite: 'en_stock', produit_mis_en_avant: false, date_creation: now, date_modification: now },
  { id: 'packaging-cosmetique', name: 'Packaging Cosmétique Complet', price: 1200, category: 'parfumerie-cosmetique', subcategory: 'Packaging cosmétique', images: [packCosmetique], description: 'Solution complète packaging cosmétique : boîtes, étiquettes et flacons assortis.', minQty: 50, productionDelay: '10-14 jours', isCustomizable: true, stock: 2000, rating: 5.0, reviewsCount: 15, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },

  // ETIQUETTES & STICKERS
  { id: 'etiquette-produit', name: 'Étiquettes Produits', price: 95, category: 'etiquettes-stickers', subcategory: 'Étiquettes', images: [objetsPublicitaires], description: 'Étiquettes personnalisées pour tous types de produits, alimentaires et cosmétiques.', minQty: 500, productionDelay: '3-5 jours', isCustomizable: true, stock: 50000, rating: 4.8, reviewsCount: 67, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
  { id: 'sticker-logo', name: 'Stickers Logo', price: 75, category: 'etiquettes-stickers', subcategory: 'Stickers', images: [objetsPublicitaires], description: 'Stickers personnalisés avec votre logo, résistants à l\'eau et aux UV.', minQty: 500, productionDelay: '3-5 jours', isCustomizable: true, stock: 40000, rating: 4.7, reviewsCount: 43, disponibilite: 'en_stock', produit_mis_en_avant: false, date_creation: now, date_modification: now },

  // EVENEMENTIEL
  { id: 'kit-mariage', name: 'Kit Mariage Complet', price: 2500, category: 'evenementiel', subcategory: 'Mariage', images: [mariagePrestige], description: 'Kit complet mariage : bouteilles, sacs, étiquettes et cadeaux invités personnalisés.', minQty: 50, productionDelay: '10-14 jours', isCustomizable: true, stock: 1000, rating: 5.0, reviewsCount: 56, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
  { id: 'kit-bapteme', name: 'Kit Baptême', price: 1800, category: 'evenementiel', subcategory: 'Baptême', images: [mariagePrestige], description: 'Packaging complet pour baptême : étiquettes, sacs et cadeaux invités.', minQty: 50, productionDelay: '10-14 jours', isCustomizable: true, stock: 1000, rating: 4.9, reviewsCount: 34, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
  { id: 'kit-anniversaire', name: 'Kit Anniversaire', price: 1500, category: 'evenementiel', subcategory: 'Anniversaire', images: [mariagePrestige], description: 'Kit anniversaire personnalisé : ballons, étiquettes et packaging cadeaux.', minQty: 30, productionDelay: '7-10 jours', isCustomizable: true, stock: 2000, rating: 4.8, reviewsCount: 28, disponibilite: 'en_stock', produit_mis_en_avant: false, date_creation: now, date_modification: now },
  { id: 'kit-magal', name: 'Kit Magal & Gamou', price: 1200, category: 'evenementiel', subcategory: 'Magal & Gamou', images: [mariagePrestige], description: 'Packaging religieux personnalisé pour Magal et Gamou.', minQty: 100, productionDelay: '7-10 jours', isCustomizable: true, stock: 3000, rating: 4.9, reviewsCount: 41, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },

  // PACKAGING CADEAUX
  { id: 'coffret-cadeau', name: 'Coffrets Cadeaux', price: 800, category: 'packaging-cadeaux', subcategory: 'Coffrets', images: [mariagePrestige], description: 'Coffrets cadeaux élégants personnalisables pour toutes occasions.', minQty: 50, productionDelay: '7-10 jours', isCustomizable: true, stock: 3000, rating: 4.9, reviewsCount: 31, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
  { id: 'ruban-personnalise', name: 'Rubans Personnalisés', price: 120, category: 'packaging-cadeaux', subcategory: 'Accessoires cadeaux', images: [accessoiresPack], description: 'Rubans satin personnalisés avec votre texte ou logo.', minQty: 200, productionDelay: '5-7 jours', isCustomizable: true, stock: 10000, rating: 4.7, reviewsCount: 19, disponibilite: 'en_stock', produit_mis_en_avant: false, date_creation: now, date_modification: now },

  // ARTICLES PERSONNALISES
  { id: 'mug-personnalise', name: 'Mugs Personnalisés', price: 1500, category: 'articles-personnalises', subcategory: 'Vaisselle personnalisée', images: [objetsPublicitaires], description: 'Mugs céramique personnalisés avec votre logo ou photo.', minQty: 12, productionDelay: '5-7 jours', isCustomizable: true, stock: 2000, rating: 4.8, reviewsCount: 44, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
  { id: 'stylo-personnalise', name: 'Stylos Personnalisés', price: 350, category: 'articles-personnalises', subcategory: 'Goodies', images: [objetsPublicitaires], description: 'Stylos publicitaires personnalisés avec votre logo.', minQty: 100, productionDelay: '5-7 jours', isCustomizable: true, stock: 10000, rating: 4.6, reviewsCount: 22, disponibilite: 'en_stock', produit_mis_en_avant: false, date_creation: now, date_modification: now },
  { id: 'tshirt-personnalise', name: 'T-shirts Personnalisés', price: 3500, category: 'articles-personnalises', subcategory: 'Textile', images: [objetsPublicitaires], description: 'T-shirts personnalisés impression sérigraphie ou DTF.', minQty: 10, productionDelay: '7-10 jours', isCustomizable: true, stock: 5000, rating: 4.9, reviewsCount: 38, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },

  // SOLUTIONS IMPRESSION
  { id: 'carte-visite', name: 'Cartes de Visite', price: 500, category: 'solutions-impression', subcategory: 'Supports commerciaux', images: [objetsPublicitaires], description: 'Cartes de visite premium, finition mat ou brillant, 350g.', minQty: 100, productionDelay: '3-5 jours', isCustomizable: true, stock: 20000, rating: 4.8, reviewsCount: 89, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
  { id: 'flyer', name: 'Flyers & Dépliants', price: 250, category: 'solutions-impression', subcategory: 'Supports commerciaux', images: [objetsPublicitaires], description: 'Flyers A5/A4 couleur recto-verso, papier couché 135g.', minQty: 500, productionDelay: '3-5 jours', isCustomizable: true, stock: 30000, rating: 4.7, reviewsCount: 62, disponibilite: 'en_stock', produit_mis_en_avant: false, date_creation: now, date_modification: now },
  { id: 'roll-up', name: 'Roll-up & Kakémonos', price: 18000, category: 'solutions-impression', subcategory: 'Affichage publicitaire', images: [objetsPublicitaires], description: 'Roll-up 80x200cm avec structure aluminium, impression HD.', minQty: 1, productionDelay: '3-5 jours', isCustomizable: true, stock: 500, rating: 4.9, reviewsCount: 47, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },

  // SOLUTIONS ENTREPRISES
  { id: 'kit-entreprise', name: 'Kit Communication Entreprise', price: 5000, category: 'solutions-entreprises', subcategory: 'Communication visuelle', images: [objetsPublicitaires], description: 'Kit complet communication : cartes de visite, flyers, roll-up et stylos.', minQty: 1, productionDelay: '7-10 jours', isCustomizable: true, stock: 500, rating: 5.0, reviewsCount: 23, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
  { id: 'cadeau-entreprise', name: 'Coffrets Cadeaux Entreprise', price: 8500, category: 'solutions-entreprises', subcategory: 'Cadeaux d\'entreprise', images: [packCosmetique], description: 'Coffrets cadeaux d\'entreprise personnalisés, idéaux pour clients et collaborateurs.', minQty: 10, productionDelay: '10-14 jours', isCustomizable: true, stock: 1000, rating: 4.9, reviewsCount: 17, disponibilite: 'en_stock', produit_mis_en_avant: true, date_creation: now, date_modification: now },
];